### ISSUE TITLE
Title not showed with Icon and if Icon is nil showed empty space

### ISSUE THREAD

**Issue by VladK9** [gianpispi/Bauletto#8]
**If icon is nil**
`let settings = BaulettoSettings(icon: nil,
                                            title: "Test title", dismissMode: .never)
            Bauletto.show(withSettings: settings)`
![IMG_6142](https://user-images.githubusercontent.com/50109143/97018521-ac834c00-1568-11eb-8d08-7bfd146afbb0.jpg)

**with icon** 
`let settings = BaulettoSettings(icon: UIImage(systemName: "checkmark.seal.fill"),
                                            title: "Test title", dismissMode: .never)
            Bauletto.show(withSettings: settings)`
![IMG_6141](https://user-images.githubusercontent.com/50109143/97018530-aee5a600-1568-11eb-8f1f-41258d8237e5.jpg)

**Comment by gianpispi** [comment]
Hi VladK9,

A fix is coming. Thanks for pointing it out.

Gianpiero

**Comment by gianpispi** [comment]
It should work now. If it is not, please feel free to reopen this issue.

Thank you,
Gianpiero
